import covidSlice, { fetchApi } from '../redux/api/api';

const initial = {
  covid: [
    {
      country: 'Ghana',
      cases: '16',
      continent: 'Africa',
      todayCases: '123',
      todayDeaths: '44',
      recovered: '23',
      todayRecovered: '34',
      active: '123',
      critical: '20',
      population: '102',
    },
    {
      country: 'Nigeria',
      cases: '17',
      continent: 'Africa',
      todayCases: '120',
      todayDeaths: '47',
      recovered: '25',
      todayRecovered: '38',
      active: '163',
      critical: '21',
      population: '122',
    },
    {
      country: 'South Africa',
      cases: '11',
      continent: 'Africa',
      todayCases: '13',
      todayDeaths: '40',
      recovered: '21',
      todayRecovered: '14',
      active: '113',
      critical: '21',
      population: '112',
    },
    {
      country: 'USA',
      cases: '11',
      continent: 'North America',
      todayCases: '163',
      todayDeaths: '48',
      recovered: '20',
      todayRecovered: '54',
      active: '183',
      critical: '200',
      population: '1234',
    },
    {
      country: 'Japan',
      cases: '50',
      continent: 'Asia',
      todayCases: '127',
      todayDeaths: '40',
      recovered: '27',
      todayRecovered: '35',
      active: '103',
      critical: '200',
      population: '1102',
    },
  ],
};

describe('Check if the reducer works properly', () => {
  const covidData = [
    {
      country: 'Ghana',
      cases: '16',
      continent: 'Africa',
      todayCases: '123',
      todayDeaths: '44',
      recovered: '23',
      todayRecovered: '34',
      active: '123',
      critical: '20',
      population: '102',
    },
    {
      country: 'Nigeria',
      cases: '17',
      continent: 'Africa',
      todayCases: '120',
      todayDeaths: '47',
      recovered: '25',
      todayRecovered: '38',
      active: '163',
      critical: '21',
      population: '122',
    },
    {
      country: 'South Africa',
      cases: '11',
      continent: 'Africa',
      todayCases: '13',
      todayDeaths: '40',
      recovered: '21',
      todayRecovered: '14',
      active: '113',
      critical: '21',
      population: '112',
    },
    {
      country: 'USA',
      cases: '11',
      continent: 'North America',
      todayCases: '163',
      todayDeaths: '48',
      recovered: '20',
      todayRecovered: '54',
      active: '183',
      critical: '200',
      population: '1234',
    },
    {
      country: 'Japan',
      cases: '50',
      continent: 'Asia',
      todayCases: '127',
      todayDeaths: '40',
      recovered: '27',
      todayRecovered: '35',
      active: '103',
      critical: '200',
      population: '1102',
    },
  ];

  test('Test if coins are loaded correctly', () => {
    expect(covidSlice(initial, fetchApi(covidData)).covid).toEqual(covidData);
  });
});
